 spring:
   data:
     mongodb:
       host: ds119486.mlab.com
       port: 19486
       database: laboratorio7
       username: laboratorio7
       password: Arsw1234
 redis:
   host: 127.0.0.1
   port: 6379
